apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: cloudpoc.azurecr.io/consumer:v1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cloudpoc
spec:
  type: ClusterIP
  ports:
    - port: 8081
  selector:
    app: cloud-poc
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudpoc
  annotations:
    #kubernetes.io/ingress.class: addon-http-application-routing
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    #- host: springbootdocker.1438e5dcdd7d432ab540.westus3.aksapp.io
    - host: example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: springbootdocker
                port:
                  number: 8080