apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: cloudpoc.azurecr.io/consumer:v1
          ports:
            - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  # Name of our service
  name: cloud-poc-service
spec:
  # LoadBalancer type to allow external access to multiple ports
  type: LoadBalancer
  selector:
    # Will deliver external traffic to the pod holding each of our containers
    app: consumer
  ports:
    #- name: sentiment
      #protocol: TCP
     - port: 8081
      #targetPort: containerport